// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const buildDatabaseUrl = () => {
  if (process.env["DATABASE_URL"]) {
    return process.env["DATABASE_URL"];
  }

  const host = process.env["DB_HOST"] ?? "localhost";
  const port = process.env["DB_PORT"] ?? "3306";
  const user = encodeURIComponent(process.env["DB_USER"] ?? "root");
  const password = encodeURIComponent(process.env["DB_PASSWORD"] ?? "password");
  const database = process.env["DB_NAME"] ?? "umc_10th";

  return `mysql://${user}:${password}@${host}:${port}/${database}`;
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: buildDatabaseUrl(),
  },
});
